image: $CI_REGISTRY/linux-wiiu/linux-loader/ci

stages:
    - container
    - build

container-build:
    stage: container
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
        - docker build -t "${CI_REGISTRY}/linux-wiiu/linux-loader/ci" .
        - docker push "${CI_REGISTRY}/linux-wiiu/linux-loader/ci"
    only:
        changes:
            - Dockerfile

loader-build:
    stage: build
    script:
    - sed s/B5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DEFINITELY_LEGAL}/g -i castify.py
    - sed s/91XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DO_THEY_EVEN_CARE}/g -i castify.py
    - make
    artifacts:
        paths:
        - fw.img
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
