image: $CI_REGISTRY/linux-wiiu/linux-loader/ci

stages:
    - container
    - build

container-build:
  stage: container
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY}/linux-wiiu/linux-loader/ci"

loader-build:
    stage: build
    script:
    - sed s/B5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DEFINITELY_LEGAL}/g -i castify.py
    - sed s/91XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DO_THEY_EVEN_CARE}/g -i castify.py
    - make
    artifacts:
        paths:
        - fw.img
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
