name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20250102

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: '25'

      #workaround for the github checkout not fully working right with containers
      #see : https://github.com/actions/checkout/issues/2031
    - name: Add git safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Python install
      run: sudo apt-get update -y && sudo apt-get install --no-install-recommends -y python3 python3-pycryptodome

    - name: Build wiiu-loader
      run: |
        make -j$(nproc)

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: fw.img
